### ISSUE TITLE
OOM when running with valgrind

### ISSUE THREAD

**Issue by Jimmy316** [alicevision/CCTag#101]
I tried to run valgrind on the detection algorithm. I see memory consumption go up continously. It reaches 15GB and kills my wks. Have any of you encountered similar issues

**Comment by Jimmy316** [comment]
This is the command I am running 
valgrind --leak-check=yes --track-origins=yes --log-file=cctag.out --leak-check=full --show-leak-kinds=all ./detection -n 3 -i sample01.png

**Comment by Jimmy316** [comment]
Running within an Ubuntu 16.04 docker container.

**Comment by simogasp** [comment]
Just to know, are you using the cuda version or the cpu version? Do you have the same if u run it with `--use-cuda`?

**Comment by Jimmy316** [comment]
I am using the stand alone version (i.e the non cuda version) I didn't build a library with the CUDA version. I can give it a shot next.

**Comment by simogasp** [comment]
I was asking because in the cuda version there are a lot of dynamic allocations but it should not be the case in the cpu.
Can u post the log or the result of valgrind?

**Comment by Jimmy316** [comment]
Hi 

I got on a server that has 128GB of memory and ran the test. I see the total memory consumption goes upto 25GB (that explains why it didn't run on my laptop) 

Find the valgrind output attached
[valgrind_cctag.log](https://github.com/alicevision/CCTag/files/3154132/valgrind_cctag.log)
