### ISSUE TITLE
Crash in outlierRemoval

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/CCTag#114]
I get a crash and the debugger says that it is here:
https://github.com/alicevision/CCTag/blob/7768c184d4107d389ef1c0a086a7f55d28d542de/src/cctag/Vote.cpp#L570
`vDistFinal` is empty, so `numerical::medianRef` crashes as it accesses to an element of the vector in all cases.

I have not submitted a PR, as I'm not sure what I'm supposed to return in this case.

**Comment by simogasp** [comment]
@lcalvet

**Comment by lcalvet** [comment]
You can return a very high value, such as for example the one [there](https://github.com/alicevision/CCTag/blob/7768c184d4107d389ef1c0a086a7f55d28d542de/src/cctag/Detection.cpp#L138). The filteredChildren vector is also empty in that case, the candidate will be discarded [there](https://github.com/alicevision/CCTag/blob/7768c184d4107d389ef1c0a086a7f55d28d542de/src/cctag/Detection.cpp#L150) anyway.
