### ISSUE TITLE
CvMat::CvMat(cv::Mat) depricated in OpenCV 3.4.9

### ISSUE THREAD

**Issue by wbblom** [alicevision/CCTag#120]
I have OpenCV 3.4.9 Installed and can't build CCTag develop branch from source.
To reproduce:
- Ubuntu 18.04
- CMake 3.16.3
- Boost 1.66
- OpenCV 3.4.9
- Build CCTag from source with -DCCTAG_WITH_CUDA=0 -DCCTAG_ENABLE_SIMD_AVX2=ON -DBUILD_SHARED_LIBS=ON

Errors:
[  2%] Building CXX object src/CMakeFiles/CCTag.dir/cctag/filter/cvRecode.cpp.o
~/Downloads/CCTag/src/cctag/filter/cvRecode.cpp: In function ‘void cvRecodedCanny(const cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, float, float, int, int, const cctag::Parameters*)’:
~/Downloads/CCTag/src/cctag/filter/cvRecode.cpp:48:20: error: conversion from ‘const cv::Mat’ to non-scalar type ‘CvMat’ requested
   CvMat srcCvMat = imgGraySrc;
                    ^~~~~~~~~~
~/Downloads/CCTag/src/cctag/filter/cvRecode.cpp:51:20: error: conversion from ‘cv::Mat’ to non-scalar type ‘CvMat’ requested
   CvMat dstCvMat = imgCanny;
                    ^~~~~~~~
~/Downloads/CCTag/src/cctag/filter/cvRecode.cpp:54:19: error: conversion from ‘cv::Mat’ to non-scalar type ‘CvMat’ requested
   CvMat dxCvMat = imgDX;
                   ^~~~~
~/Downloads/CCTag/src/cctag/filter/cvRecode.cpp:57:19: error: conversion from ‘cv::Mat’ to non-scalar type ‘CvMat’ requested
   CvMat dyCvMat = imgDY;
                   ^~~~~
~/Downloads/CCTag/src/cctag/filter/cvRecode.cpp:90:39: error: no matching function for call to ‘CvSize::CvSize(int&, int&)’
   size = CvSize(src->width,src->height);
                                       ^

**Comment by wbblom** [comment]
I have created my own version of cvRecode.cpp using cv::Mat instead of CvMat which does compile with the tags as mentioned above. If you want it tell me where to upload/commit/contribute it.

**Comment by simogasp** [comment]
that would be great!
You can fork this repository and make a pull request with the new version
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by wbblom** [comment]
yes, i will do that this week

**Comment by wbblom** [comment]
should i also make the file clean? there is a lot of commented/debug/alternative code that never gets reached

**Comment by simogasp** [comment]
if you are talking about the code inside `if(use1Dkernel)` we need to ask to @lcalvet @griwodz 
It would be nice to end up with a clean code!

**Comment by wbblom** [comment]
yes, that (although I also had to fix this to be able to compile). But also the defines on lines 34 and 35, the commented debug code on line 337, the huge dump to std::cout on line 467

how do we reach @lcalvet and @griwodz ?

**Comment by simogasp** [comment]
> yes, that (although I also had to fix this to be able to compile). But also the defines on lines 34 and 35,

Those are actually used by default. Again, I don't know if we need to keep the switch option or we can just keep the code inside those branches (as it is used today)

> the commented debug code on line 337,

I think that can be removed

> the huge dump to std::cout on line 467
> 

this I don't know but at least it should be replaced by a `CCTAG_COUT_DEBUG`

> how do we reach @lcalvet and @griwodz ?

we mentioned them, they will show up :-)

**Comment by wbblom** [comment]
I created a **Draft** Pull Request named: "now CCTag builds with OpenCV3.4.9 #121".
When @lcalvet and @griwodz show up, we can see about the remaining code changes

**Comment by wbblom** [comment]
Allright now it's merged with develop, we can close this issue
