### ISSUE TITLE
Wrong id detected - nCrowns = 4

### ISSUE THREAD

**Issue by tomasdrinovsky** [alicevision/CCTag#122]
Hello,
I have come across interesting bug in detection algorithm, where two visually distinct cctags get recognized as same id (both are identified as id=95).

Image: 
![94_95](https://user-images.githubusercontent.com/31925978/77763453-64846100-703b-11ea-8003-758192432960.png)

Code:
```
cctag::Parameters params(4); 
params.setUseCuda(false);
cctag::CCTagMarkersBank bank(params._nCrowns);
cctag::CCTag::List markers;
cctagDetection(markers, 0, 0, cv_mat, params, bank);
```

Could you please confirm the problem?

**Comment by simogasp** [comment]
![cctagIssue](https://user-images.githubusercontent.com/1331744/77769595-5850d180-7044-11ea-8e6e-d8ffa39e2766.png)

Yes
@lcalvet any clue?

**Comment by tomasdrinovsky** [comment]
Thanks for confirmation.

I have found other such pairs [62, 63], [94, 95], [110, 111], [118, 119].
The pattern here is that all of them have only change in inner most black circle.

My markers were generated using values in array idFourCrowns located in CCTagMarkersBank.cpp.

**Comment by fabiencastan** [comment]
@tomasdrinovsky When you have misidentifications for instance between 94-95. Does it always detects 95 instead of 94 repeatably? Or is there some randomness?

**Comment by lcalvet** [comment]
Dear all,
The detection of the CCTags composed of 4 black rings is not functional at all. Fixing it requires a lot of work. Markers that must be used are the ones located in markersToPrint folder (3 black rings).
Sorry for that.

**Comment by tomasdrinovsky** [comment]
@fabiencastan 100% reproducibility in any angle, zoom etc.
@lcalvet thanks for information. Unfortunatelly 3 ring markers offer too limited range of ids for my application :(

**Comment by zhiyu2020** [comment]
Have you solve the problems. I have the same question.
