### ISSUE TITLE
crash in CUDA-side identify in copy device-to-host

### ISSUE THREAD

**Issue by griwodz** [alicevision/CCTag#13]
Destination of a stack variable, not pinned memory. Should work but doesn't. Make sure the destination is pinned memory.

**Comment by griwodz** [comment]
Replaced stack variable with pinned memory buffer in branch popart_demo.

**Comment by griwodz** [comment]
another possible pinning-related problem in Tag::load()

**Comment by simogasp** [comment]
@griwodz is it solved?

**Comment by griwodz** [comment]
Pretty sure this is solved.
