### ISSUE TITLE
[question] Why is boost 1.66 needed?

### ISSUE THREAD

**Issue by elektrokokke** [alicevision/CCTag#139]
**Describe the problem**
I recently built CCTag on Ubuntu Bionic (18.04). Stock boost version there is 1.65, thus CCTag does not build out of the box. Changing the boost version is not that easily possible, as a lot software (at least on my system) depends on Boost 1.65. Having another Boost version somewhere else in parallel means building Boost yourself.

So, I just changed the required version to 1.65 in the CMakeLists.txt, and it built perfectly.

Do I have to expect some caveats or is the 1.66 requirement just somewhat arbitrary because it was never tried with 1.65?

Thanks a lot.

**Comment by simogasp** [comment]
It is possible that lower boost versions are compatible, 1.66 is the version that has been used to develop the most recent changes and the port to windows. Indeed it may be related to the use of stacktrace under windows 
see https://github.com/alicevision/CCTag/commit/d1e18a2af46c0d1d33aad97bf16843fe7075fd50

So we choose to have a common minimum version requirement for all platforms. 
Maintaining the minimum version that also matches the versions shipped with each distribution can quickly become a living hell... :-)
