### ISSUE TITLE
[question] Which MarkerId to use in Meshroom SfMTransform node

### ISSUE THREAD

**Issue by guizy67** [alicevision/CCTag#141]
CCTag markers to be printed are clearly numbered from 1 to 32.

However in this guide, the markers are numbered 0 and 1, whereas they look like markers 1 and 1.
https://github.com/alicevision/meshroom/wiki/CCTAG-scaling

So just to be clear, which numbering is correct, 0-31 or 1-32?

FYI I have followed the above guide and have tried both numberings and currently the SfMTransform node is not matching my markers. Any hints would be useful.

**Comment by simogasp** [comment]
yes u are right there is an inconsistency.
The ids go 0-31 we should rename the marker to print
