### ISSUE TITLE
[question] eigen 3.3.9 win

### ISSUE THREAD

**Issue by irmadibra** [alicevision/CCTag#144]
I am trying to run the CCTAG project on windows the feature below is needed?
In order to have Cuda support on Windows, at least Eigen 3.3.9 is required.
 However the last version at the moment of eigen i could find is 3.3.8 but not working any suggestions?

**Comment by simogasp** [comment]
Yes there is an upcoming release of eigen, meanwhile you can just pull the repository https://gitlab.com/libeigen/eigen, the latest version has the needed patch

**Comment by simogasp** [comment]
eigen 3.3.9 is out now https://gitlab.com/libeigen/eigen/-/releases/3.3.9
