### ISSUE TITLE
detection coordinate outliers

### ISSUE THREAD

**Issue by wi6436** [alicevision/CCTag#145]
I have a fixed CCTV camera pointed to a fixed 3-ring tag. The tag appears with a diameter of ~160 pixels in the recorded image. I retrieve a new jpg frame from the camera periodically, I apply the detection sample program and log the detected coordinates.

The noise performance of the detected coordinates is usually (>99.9% of images) excellent and the coordinates stay constant fluctuating only within a < +/-0.2 pixel deviation range.

However, very rarely (<0.1% of images), I see isolated outliers in the detected coordinates with deviations >6 pixels. The images producing such outliers look (with the naked eye) absolutely identical to the ones not producing outliers (no position offset, no change in lighting).

Has anybody seen a similar effect or has an idea what could cause that? The bug might be in CCTag or in the camera (though invisible to the eye). Which position resolution can CCTag achieve in general?

Thank you very much for any ideas.

**Comment by simogasp** [comment]
Would it be possible for you to share some images (some "good" and "bad" images) so we can reproduce the problem?
