### ISSUE TITLE
[question] upscaling vs. parameter change for small target detection

### ISSUE THREAD

**Issue by Huemerj** [alicevision/CCTag#150]
The target detection works quite well if a target is big enough, compared to the size of the whole image. 
If this is not the case, i.e. if the target is really small (30px in a 1400px image), the target is not detected anymore.
So in order to detect a target in a comparatively big image, I can crop the target and then up-scale the cropped image part. Then I can detect the target reliably in the up-scaled image part.

My question is now: Is there are more feasible and natural way to detect small targets? By e.g. changing the default parameters? If yes, which parameters are responsible for multi-scale detection?
Thank you for your suggestions!

**Comment by MrIsland** [comment]
Hi!

**Comment by MrIsland** [comment]
Hi !

Did you ever manage to solve this question ? I happen to have the same problem as you and want to ask if anyone else knows of the solution to this problem? 

Sorry to bother you, many thanks.
