### ISSUE TITLE
why it often cannot detect the rings with very good picture using default parameters[question]

### ISSUE THREAD

**Issue by yeguoqiang11** [alicevision/CCTag#157]
**Describe the problem**
creating a board with a lot of tags, but it can only detect half of them using default parameters, my board image is as good as following image:
![Screenshot from 2021-04-02 16-20-14](https://user-images.githubusercontent.com/81662082/113398258-e0448680-93d0-11eb-9355-de34f8e41340.png)

**Comment by lcalvet** [comment]
You may try to change the value of MAX_MARKER_FOR_IDENT in ccta/cuda/onoff.h to something greater than 60, e.g. 100.
Don’t increase it too aggressively: this is pinned memory that CCTag will keep in the computer’s physical memory (not only virtual memory) until the end of the program.

**Comment by yeguoqiang11** [comment]
> You may try to change the value of MAX_MARKER_FOR_IDENT in ccta/cuda/onoff.h to something greater than 60, e.g. 100.
> Don’t increase it too aggressively: this is pinned memory that CCTag will keep in the computer’s physical memory (not only virtual memory) until the end of the program.

thank you. when i print ten tags in image, it cannot detect all. what about other parameters.

**Comment by lcalvet** [comment]
Please share the input images along with your results for your failure cases.
