### ISSUE TITLE
what is accuracy from distortion and perspective transformation of tags[question]

### ISSUE THREAD

**Issue by yeguoqiang11** [alicevision/CCTag#158]
as i want to use cctag to calibrate the cameras, and cameras is a fisheye with big fov(240 degree), can it get what accuracy of tags.  fisheye has a big radical distortion, and we get the image from different angles, so it is important for us to get high accuracy localization position to get a good intrinsics from difficult situation. thank you very much.

**Comment by lcalvet** [comment]
It all depends on the size of the imaged cctags. If they are small enough s. t. their boundaries are nearly ellipses, they will be detected. The detection algorithm assume a pinhole camera model.
