### ISSUE TITLE
[question] How can I detect all in one paper which contain 114 same cctags with a boundary of images?

### ISSUE THREAD

**Issue by zhiyu2020** [alicevision/CCTag#159]
**Describe the problem**
I compile cctag and use it to detect a picture with 114 cctags. However I cannot detect all cctags. Normally I get only 110 - 114 tags. I have 12 picutres. How can I detect all tags in pics without adjusting params?
**Screenshots**
![image](https://user-images.githubusercontent.com/38719444/114000287-6f4c1580-988d-11eb-9b76-b255544db3d8.png)

![image](https://user-images.githubusercontent.com/38719444/114000484-a1f60e00-988d-11eb-81f6-c30d4fc1faa5.png)
![image](https://user-images.githubusercontent.com/38719444/114000531-af12fd00-988d-11eb-8a57-10ce588759e3.png)
![image](https://user-images.githubusercontent.com/38719444/114000709-d073e900-988d-11eb-913d-c4561b05d96d.png)
![image](https://user-images.githubusercontent.com/38719444/114000748-dbc71480-988d-11eb-9a71-42578856dd1b.png)

**Comment by lcalvet** [comment]
You should first of all respect the required margins (see warning https://github.com/alicevision/CCTag) between cctag-pairs et between cctag and image or page boundaries.
If you still face the problem, please post the input images and your detection results.

**Comment by zhiyu2020** [comment]
- I plan to upload the pictures, these pictures are made up from photos taken by real scene. part of raw imgs are as follows:

[concentric.zip](https://github.com/alicevision/CCTag/files/6293245/concentric.zip)

-  I modify the the configs  to adjust detection rate.
![image](https://user-images.githubusercontent.com/38719444/114328851-6cdd0a80-9b70-11eb-8bbc-bf282d4b8d9d.png)
- the pictures I input are here. I hope you can help me test these pictures and give me advice. Thanks!


[test.zip](https://github.com/alicevision/CCTag/files/6293225/test.zip)
[test1.zip](https://github.com/alicevision/CCTag/files/6293230/test1.zip)
[test2.zip](https://github.com/alicevision/CCTag/files/6293235/test2.zip)
[test3.zip](https://github.com/alicevision/CCTag/files/6293237/test3.zip)

**Comment by zhiyu2020** [comment]
- **I have a problem about brightness. I think this program has something wrong with brightness. I control the same parameter and input img. But I get the different result.** (PS. I decrease the lightness of the simulation img). Maybe you can try this picture.
[concentric2_lowerbright.zip](https://github.com/alicevision/CCTag/files/6310517/concentric2_lowerbright.zip)
- the screenshot below are the different result with same input img.
![image](https://user-images.githubusercontent.com/38719444/114703979-9eb0c580-9d58-11eb-8bae-2552c01ff74b.png)
![image](https://user-images.githubusercontent.com/38719444/114703992-a2444c80-9d58-11eb-8ec9-b7aa0a1acf46.png)
![image](https://user-images.githubusercontent.com/38719444/114704004-a6706a00-9d58-11eb-89b3-8e599f7b2f99.png)
![image](https://user-images.githubusercontent.com/38719444/114704016-aa03f100-9d58-11eb-81cf-c000b7313eb7.png)

**Comment by zhiyu2020** [comment]
![image](https://user-images.githubusercontent.com/38719444/114704183-e3d4f780-9d58-11eb-8f4a-e1d9f4283bba.png)
- The parameters are above. I hope it will help you fix the bug.
