### ISSUE TITLE
[bug] Current vcpkg compilation is not working out of the box

### ISSUE THREAD

**Issue by Blup1980** [alicevision/CCTag#167]
I recently installed vcpkg on windows 10 along with VS2019 community.

I ran:

`vcpkg install cctag[cuda,apps]:x64-windows`

It crashes even after manually applying the fix for the known issue #166 

The problem appears : 
`Creating library src\CCTagd.lib and object src\CCTagd.exp
Bresenham.cpp.obj : error LNK2019: unresolved external symbol "int __cdecl boost::math::sign<int>(int const &)" (??$sign@H@math@boost@@YAHAEBH@Z) referenced in function "void __cdecl cctag::updateXY(float const &,float const &,int &,int &,float &,int &,int &)" (?updateXY@cctag@@YAXAEBM0AEAH1AEAM11@Z)
Windows-AMD64\CCTagd.dll : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.`

Is seems to be linked with issue #166 that added the line in Bresenham.cpp:
`#include <boost/math/special_functions/sign.hpp>`
But without informing CMAKE that boost::math is used.

**Desktop:**
 - OS: Windows 10 x64
 - Cuda version CUDA V11.4.100
 - Boost 1.76
 - CCTag version: 1.0.0 from the vcpkg repository

**Comment by simogasp** [comment]
Thanks for reporting that.
Does adding `boost::math` to cmake fix the problem?
boost::math is headers only (except for few functions not used here), it's strange that the compilation passed on vcpkg CI. And on my side, I didn't have this problem with a build from scratch. Or maybe it's the new version of boost that changed the structure of the files or something. I'll try to test again

Anyway, if that fixes the problem we can then make a new patch release and a PR to vcpkg.

**Comment by Blup1980** [comment]
Yes, indeed adding the lib to CMake fixed the problem.
I had already fixed it, but the workflow here is to first create an issue and then resolve it in a PR. ;-)
