### ISSUE TITLE
[bug] vcpkg compilation error : BOOST_NO_CXX11_NOEXCEPT

### ISSUE THREAD

**Issue by Blup1980** [alicevision/CCTag#169]
I recently installed vcpkg on windows 10 along with VS2019 community.

I ran:

`vcpkg install cctag[cuda,apps]:x64-windows`

It crashes even after manually applying the fix for the known issue #166 and #167

The complain was that BOOST_NO_CXX11_NOEXCEPT is no longer supported in Boost from March 2021
I had a look where BOOST_NO_CXX11_NOEXCEPT is defined and found one file : cctag_cuda_runtime.h

```
/*
 * Copyright 2016, Simula Research Laboratory
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#pragma once

#ifdef __CUDACC__
 //
 // When compiling .cu files, there's a bunch of stuff that doesn't work with msvc:
 //
#if defined(_MSC_VER)
#  define BOOST_NO_CXX14_DIGIT_SEPARATORS
#  define BOOST_NO_CXX11_UNICODE_LITERALS
#  define BOOST_PP_VARIADICS 0
#endif
#  define BOOST_NO_CXX11_DEFAULTED_FUNCTIONS
#endif

#include <cuda_runtime.h>


 // https://svn.boost.org/trac/boost/ticket/11897
 // This is fixed in 7.5. As the following version macro was introduced in 7.5 an existance
 // check is enough to detect versions < 7.5
 #if BOOST_CUDA_VERSION < 7050000
 #   define BOOST_NO_CXX11_VARIADIC_TEMPLATES
 #endif
 // The same bug is back again in 8.0:
 #if (BOOST_CUDA_VERSION > 8000000) && (BOOST_CUDA_VERSION < 8010000)
 #   define BOOST_NO_CXX11_VARIADIC_TEMPLATES
 #endif
 // Most recent CUDA (8.0) has no constexpr support in msvc mode:
 #if defined(_MSC_VER)
 #  define BOOST_NO_CXX11_CONSTEXPR
 #endif

#ifdef __CUDACC__
// And this one effects the NVCC front end,
// See https://svn.boost.org/trac/boost/ticket/13049
//
#if (BOOST_CUDA_VERSION >= 8000000) && (BOOST_CUDA_VERSION < 8010000)
#  define BOOST_NO_CXX11_NOEXCEPT
#endif

#endif
```

The comment in the .h said "Most recent CUDA (8.0) has no constexpr support in msvc mode"
But using the recent CUDA V11.4.100 it seems to be supported.
removing the BOOST_NO_CXX11_NOEXCEPT  led to a successful compilation of the CUDA files.

I removed the following lines and with fix #166 and #167 it compiled sucessfully.
```
#if defined(_MSC_VER)
#  define BOOST_NO_CXX11_CONSTEXPR
#endif
```

**BUT:**

Theses lines of code were here for a good reason. I suppose we should add some condition on the MSVC version, CUDA version, and BOOST version to disable this line.

As it is, I don't know what these conditions are but it compiles with the following configuration which are the default from a clean vcpkg install:

**Desktop:**
 - OS: Windows 10 x64
 - CUDA V11.4.100
 - Boost 1.76
 - VS2019 Community Edition
 - CCTag version: 1.0.0 from the vcpkg repository

**Comment by simogasp** [comment]
I think everything can be removed now.
We now are requiring c++14, so we can forget about those CXX* definitions and since nvcc only supports c++14 starting from cuda 10, also the other definitions can be dropped.
And we should also raise the minimum cuda version from 7 to 10.
You can try to comment all those define out and see what happens

**Comment by simogasp** [comment]
I confirm that removing `BOOST_NO_CXX11_NOEXCEPT` and `BOOST_NO_CXX11_CONSTEXPR` everything works on windows.

@griwodz do you think we can safely remove all these definitions now that we are requiring c++14, so we only deal with cuda > 9 and more recent versions of msvc > 19
