### ISSUE TITLE
CUDA detection not working Windows 10

### ISSUE THREAD

**Issue by nicolasdp88** [alicevision/CCTag#170]
I successfully compiled cctag from the develop branch.

Dependencies are from vcpkg, with a slight patch to fix Boost constexpr issues.

CCTag develop is configured like this :

`cmake -DCMAKE_TOOLCHAIN_FILE="[..]/vcpkg.cmake" -DCCTAG_ENABLE_SIMD_AVX2=ON -DBUILD_SHARED_LIBS=ON -DCCTAG_WITH_CUDA=ON -DCCTAG_CUDA_CC_CURRENT_ONLY=ON ..`

It compiles fine in Release.

When running detection.exe on the samples, I get the expected result using CPU, but as soon as I use CUDA I get no candidates detected.

`Creating TagPipe 0
Initializing TagPipe 0
Loading image 0 into TagPipe 0
Total time:  0.228465s wall, 0.093750s user + 0.125000s system = 0.218750s CPU (95.7%)

#frame 0
Detected 0 candidates

0 markers detected and identified`

Window 10 x64
VS2019
Boost 1.76
CUDA V11.4.100
CCTag develop from github

RTX3070, if it changes anything.

**Comment by Blup1980** [comment]
I observe the same behavior using the exact same version as you (CUDA and boost) except that I have a Quadro P1000.

**Comment by cristian893** [comment]
Hi,

I have the same issue, but running on Ubuntu. When detection script is running on CPU everything is OK, detect the candidates, but when is running on GPU I have zero detected candidates.

Did you solved this?

Thank you!

**Comment by simogasp** [comment]
> Hi,
> 
> I have the same issue, but running on Ubuntu. When detection script is running on CPU everything is OK, detect the candidates, but when is running on GPU I have zero detected candidates.
> 
> Did you solved this?
> 
> Thank you!

Which card do you have?

**Comment by cristian893** [comment]
Hi,
Nvidia GTX 1050 TI

**Comment by griwodz** [comment]
I did a clean install and now I'm getting the same on the 1080. Clearly something went really wrong after fixing the CPU-side code. I'm afraid figuring it out will take a while :-(

**Comment by cristian893** [comment]
Is there older release or older version that I could try to run on GPU?

Thank you!

**Comment by nicolasdp88** [comment]
Hello all!

First time playing with CUDA, but I've got this thing working.

@griwodz 
Problem was that it was using too many threads per block when launching vote::eval_chosen in frame_07c_eval.cu.

Made the block size 24 and all works as expected. 

@simogasp 
How can I submit a patch for this? Not much of a github contributor either...

**Comment by Blup1980** [comment]
> Hello all!
> 
> First time playing with CUDA, but I've got this thing working.
> 
> @griwodz
> Problem was that it was using too many threads per block when launching vote::eval_chosen in frame_07c_eval.cu.
> 
> Made the block size 24 and all works as expected.
> 
> @simogasp
> How can I submit a patch for this? Not much of a github contributor either...

What did you changed exactly to fix the issue?
I was trying to reproduce your fix but I can't figure out exactly where you changed what.

you can post here an extract of the code that you changed.

**Comment by nicolasdp88** [comment]
@Blup1980 

Sorry I did not see this sooner.
Here is what I patched

[cuda patch.txt](https://github.com/alicevision/CCTag/files/7400446/cuda.patch.txt)

**Comment by z905762202** [comment]
@nicolasdp88  I have changed the code according to CUDa patch.txt, but still can't detect it. May I ask where is the problem? Can you give me the EXE you compiled
