### ISSUE TITLE
[bug] Missing dependency in Docker image

### ISSUE THREAD

**Issue by Blup1980** [alicevision/CCTag#175]
I tried to build the docker image using the provided information.
It worked successfully with the default Dockerfile of version 1.0.1.

I connect my terminal to my cctag container and when I run 
`/opt/cctag/build/Linux-x86_64/detection`

I get: 
`./detection: error while loading shared libraries: libboost_chrono.so.1.70.0: cannot open shared object file: No such file or directory`

Looking at the docker container alicevision/cctag-deps:cuda10.2-ubuntu18.04 that is at the base of the cctag image, I found that the libs are installed in /opt/lib

But that information is not provided to the system loader.
I had to run `echo "/opt/lib" > /etc/ld.so.conf.d/optlibs.conf`

After that, I can run ./detection from the container

I could provide this command at the end of the Dockerfile of the CCtag project. But, because it is mainly an issue with the cctag-deps docker image, I suggest to fix that image instead.

**Comment by simogasp** [comment]
yes I think we forgot to update the `LD_LIBRARY_PATH` in the docker_deps
