### ISSUE TITLE
Test docker-nvidia

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/CCTag#18]
https://github.com/NVIDIA/nvidia-docker

**Comment by xslavkov** [comment]
Hi, I would like to try CCTag in docker but link to decker-popart is not available anymore.
Is it available elsewhere (I was not able to google it) or its not public anymore?
Or is there any other docker that should work just fine?

**Comment by simogasp** [comment]
Hi @xslavkov , I think that docker is a bit outdated and above all it was meant to contain all the software we developed, not just CCTag. 
Nevertheless it would be nice to have CCTag in docker. I have no experience with docker though, if you have and you are willing to contribute it would be a really cool feature to have, and of course we can assist you.

S.
