### ISSUE TITLE
[question] marker size

### ISSUE THREAD

**Issue by simin75simin** [alicevision/CCTag#184]
**Describe the problem**
I get the idea from [this page](https://cctag.readthedocs.io/en/latest/markers/markers.html?highlight=radius#print-the-markers) that the marker shall be proportional to u / f, which I think is the upper left entry of the intrinsic matrix?
Thanks for answering in advance.

**Comment by simogasp** [comment]
it's a rule of thumb.
f is the focal length, so yes the first element of the calibration matrix.
