### ISSUE TITLE
[question] how to track like the demo video

### ISSUE THREAD

**Issue by simin75simin** [alicevision/CCTag#185]
specifically i'm referring to the demo video [here](https://www.youtube.com/watch?v=AkfnvSfWIvg&feature=emb_title)

i read in some places (see [this](https://robolab.sjtu.edu.cn/kindeditor/Upload/file/20170830/20170830144744_8958.pdf) for example) that four points on the same plane and a calibrated camera can track the camera's position and angle. but i can't find any code for this. i looked at opencv and other algorithms like solvePnP and POSIX algorithm, etc. but none of them can track the camera using only four points.

help please.

**Comment by simogasp** [comment]
The library only focuses on detection, there is no code for computing and decomposing the homography.
For that you can use opencv implementations
Estimating H from 4+ points
https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga4abc2ece9fab9398f2e560d53c8c9780
decompose H to find R and T
https://docs.opencv.org/3.1.0/d9/d0c/group__calib3d.html#ga7f60bdff78833d1e3fd6d9d0fd538d92

More info about tomography
https://docs.opencv.org/4.x/d9/dab/tutorial_homography.html

**Comment by simin75simin** [comment]
thanks!
