### ISSUE TITLE
[bug] error in detection

### ISSUE THREAD

**Issue by simin75simin** [alicevision/CCTag#188]
I'm using an rgb-depth camera (kinda like a kinect camera used in kinectfusion) to record a video stream. But sometimes cctag gives a completely wrong tag and even after removing those it still gives some random errors. 

There are about 10 tags in each image and it's shot at around 30 frames per second. The resolution is 640x480. I used the latest stable cpu version of detection and almost all of the 32 fiducials. 

Is it just not very accurate due to motion blur, low resolution, and high framerate? Are there ways to improve it without using a better camera?

I am stabilizing the camera to try to improve it for now.

**Comment by simogasp** [comment]
do you still have the issue?
In case could you share some images to test?
