### ISSUE TITLE
Problem running build/src/detection -n 3 -i sample/01.png

### ISSUE THREAD

**Issue by Akumar201** [alicevision/CCTag#197]
**Describe the problem**
While installing CCTag library I am currently at CMake configuration and using the following command 

mkdir build && cd build
cmake ..
make -j `nproc`

While running the command - $ build/src/detection -n 3 -i sample/01.png

I am getting an error -
bash: build/src/detection: No such file or directory

**Screenshots**
![Screenshot from 2022-09-13 21-01-05](https://user-images.githubusercontent.com/108360879/190035614-7655a483-0231-4d4c-bca6-f048b889abe5.png)

Error log 

[ 76%] Linking CXX shared library ../Linux-x86_64/libCCTag.so
[ 76%] Built target CCTag
Scanning dependencies of target detection
Scanning dependencies of target regression
[ 80%] Linking CXX executable ../../../../Linux-x86_64/geometry_ellipse
[ 80%] Linking CXX executable ../../../Linux-x86_64/cctag_fitEllipse
[ 82%] Linking CXX executable ../../Linux-x86_64/detection
[ 85%] Linking CXX executable ../../Linux-x86_64/regression
[ 87%] Built target cctag_fitEllipse
[ 89%] Built target geometry_ellipse
[ 95%] Built target regression
[100%] Built target detection
computer name i:~/c++/new_tag/CCTag/build$ build/src/detection -n 3 -i sample/01.png
bash: build/src/detection: No such file or directory

**Desktop (please complete the following and other pertinent information):**
 - Ubuntu 20.04
 

**Additional context**
In addition to this I would like to know can I use these tags for detection of position as Arucko Marker

**Comment by simogasp** [comment]
it's
```
./Linux-x86_64/detection  -n 3 -i sample/01.png
```

**Comment by Akumar201** [comment]
Thank you ! I was getting an error and posting it for helping anyone else

~/c++/new_tag/CCTag/build$ ./Linux-x86_64/detection  -n 3 -i sample/01.png
You called ./Linux-x86_64/detection with:
    --input     sample/01.png
    --nbrings     3
    --bank      
    --params    
    --output    


The input file "sample/01.png" is missing

I moved the sample folder to the build to run it
