### ISSUE TITLE
Detect CCTag using Video Stream

### ISSUE THREAD

**Issue by Akumar201** [alicevision/CCTag#198]
**Describe the problem**
Greetings, I am new to the library. I was able to run the detection on CCTag images in sample folder. I would like to know how can I detect the printed CCTag on from live video stream. Please provide me with a detail changes or commands that I should use to detect the CCTag with live video stream.

**Desktop (please complete the following and other pertinent information):**
Ubuntu 20.04

**Comment by simogasp** [comment]
if you used the `detection` application that comes with the library, you can just change the `input` parameter and provide an integer that refer to the camera you want to use.
Normally, if you have a webcam attached via USB, you can just pass `--input 0` and it will use the stream from that camera to process the images.
see https://github.com/alicevision/CCTag/blob/develop/src/applications/detection/CmdLine.cpp#L27

**Comment by Akumar201** [comment]
Thank you so much for your quick response. I would like to know how can I use it when I'll be making my own script in python or c++ ? Thank you

**Comment by simogasp** [comment]
In python you can call the binary but then you have to find a way to get the result. At the moment we don't have any python wrappers that enable to do the same thing as `detection` in a pure python code.
In c++, just follow the code in the `detection` source code (main.cpp) and you see how the API is used

**Comment by Akumar201** [comment]
Hello, thank you so much for your help. I would like to know is there a way I can use camera pose and distance estimation using your software. In addition to this I would like to know in future will there be pose estimation implementation of it ?

**Comment by simogasp** [comment]
no unfortunately that is not implemented at the moment.
But it should not be difficult to do following the explanations in #63 
It would be a nice contribution to add.
