### ISSUE TITLE
[question] make fails with "fatal error: 'devil_cpp_wrapper.hpp' file not found"

### ISSUE THREAD

**Issue by McCannDahl** [alicevision/CCTag#205]
**Describe the problem**
Using Mac M1, following instructions here https://cctag.readthedocs.io/en/latest/install/install.html#building-the-library, when I run "make -j `nproc`", I get the following error

**Screenshots**
<img width="612" alt="image" src="https://user-images.githubusercontent.com/19883817/210436309-917f506f-71df-4b4b-a3c4-068df070d285.png">

**Log**
I installed devil from brew, but still same error shows.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/19883817/210435808-5ee78ec1-1bfd-4b47-a54f-9c5d5201c431.png">

**Desktop**
 - OS: Mac M1
 - CCtag version: develop branch

**Comment by simogasp** [comment]
Can you try to modify the include statements and add the prefix `IL` as in 
```c++
#include <IL/devil_cpp_wrapper.hpp>
```

**Comment by McCannDahl** [comment]
Hmmm no same error
![image](https://user-images.githubusercontent.com/19883817/210454107-269fd2f9-1484-4a3c-a405-8407f9dcfac2.png)
![image](https://user-images.githubusercontent.com/19883817/210454174-79e60b56-60d3-4173-9556-8ab052ba03bd.png)

**Comment by simogasp** [comment]
It seems like that the wrapper is not installed anymore, at least in homebrew.
As a quick workaround you can comment the `find_package(DevIL COMPONENTS IL ILU)`at line 82 of `src/applications/detection/CMakeLists.txt`. Devil is only optional and if not found it will fallback to opencv for loading the images.

**Comment by McCannDahl** [comment]
That worked and the make passed. But when I run the detection example it says "Library not loaded: @rpath/libCCTag.1.0.3.dylib"
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/19883817/210640291-d04a5a77-04c7-4b02-ab67-a4c8a6df0917.png">

**Comment by simogasp** [comment]
Did you do a `make install`?
It's strange that it looks for libCCTag.dylib in `/opt/homebrew/lib/` and other system paths like that.
Usually it should be in `./build/Darwin-arm64/`.
You can try to run 
``` 
export DYLD_LIBRARY_PATH=/Users/path/to/build/Darwin-arm64/:${DYLD_LIBRARY_PATH}
```
replacing the `path/to/` with your path to the build directory. And there run `detection` as you did.

**Comment by McCannDahl** [comment]
I switched over to my PC and got it to work. We can close this for me or leave it open for other mac users
