### ISSUE TITLE
CCTag not getting linked

### ISSUE THREAD

**Issue by dkhusted** [alicevision/CCTag#212]
I am trying to make a python wrapper using code from #136, but i manage to build the project. I am very new to cmake so could use some pointers as to what i am doing wrong:
I only have one CMakeLists that builds the wrapper.

**CMakeLists.txt**

```cmake
cmake_minimum_required(VERSION 3.17.3)

project(pycctag) 

find_package(CCTag CONFIG REQUIRED)

add_subdirectory(pybind11) #cmakelists.txt and pybind11-2.5.0(or another version) folder are in same directory

pybind11_add_module(pycctag pycctag.cpp)

target_link_libraries(pycctag PUBLIC CCTag::CCTag)
`

When trying to build i get
`fatal error: CCTag/ICCTag.hpp: No such file or directory
   12 | #include <CCTag/ICCTag.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
I have installed CCTag by following the INSTALL.md, and the installation went fine.

**Comment by anand97** [comment]
Try setting CCTag_DIR with the path to your CCTag installation's cmake config files, before invoking the find command.

set(CCTag_DIR /usr/local/lib/cmake/CCTag)
