### ISSUE TITLE
hardcoded image size limits

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/CCTag#45]
There are some hardcoded limits especially MAX_RESOLUTION:
https://github.com/poparteu/CCTag/blob/develop/src/cctag/Types.hpp#L21

Is it possible to make them dynamic?
Like allocating the first time and reallocate only if size has changed?

**Comment by zvrba** [comment]
This is at the interface between CUDA and host-code. Data structures on the CUDA-side have to be preallocated, but I don't know whether these structures can be reallocated at a later time. @griwodz ?

**Comment by fabiencastan** [comment]
@griwodz Can we remove this MAX_RESOLUTION limitation?

**Comment by griwodz** [comment]
It is possible to turn the MAX_RESOLUTION into a command-line variable with limited effort. The only problem is that I'm very short on time in the coming weeks.

Dynamic resolution is harder. The memory-managing classes in CCTag are copy-pasted from OpenCV, and dynamic resolution is not possible without a major re-write (use the self-made memory classes from PopSift).

**Comment by bubulv** [comment]
how can I deal with each frame just like a new image one by one?
