### ISSUE TITLE
how to compile dynamic CCTAG_LIBRARY with cuda? 

### ISSUE THREAD

**Issue by bubulv** [alicevision/CCTag#69]
I need to dynamic invocat the cctag library as a '.so' library in Python code. 
Why the code must be static if use cuda? Could you tell me how to change these?

**Comment by griwodz** [comment]
Cuda is not the problem. The problem is that I have been unable to find out how to do it with cmake's cuda code. Your help would be appreciated.

**Comment by simogasp** [comment]
@griwodz could be this https://stackoverflow.com/a/30663344?

**Comment by bubulv** [comment]
So, just modify the cmakelist with cuda code it could be used? Do I need modify some .cu files? I have chang the cmakelist with -fpic but stell some problems！I hope you can help me.

肖旭

**Comment by simogasp** [comment]
and do `make VERBOSE=1` to check the flag is added

**Comment by bubulv** [comment]
I added "set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS};-fPIC)" after line 94 in  CCTag/src/CMakeLists.txt , it comes more issue "nvcc fatal   : Unknown option 'fPIC'"
 
![image](https://user-images.githubusercontent.com/17450562/36660418-0bddd40c-1b13-11e8-8ada-c63ea8e91e16.png)

**Comment by simogasp** [comment]
try with
`list(APPEND CUDA_NVCC_FLAGS "--compiler-options -fPIC")` instead of the previous one

**Comment by bubulv** [comment]
It dose not used."nvcc fatal   : Unknown option '-compiler-options -fPIC'"
I have try many options to add -fPIC but no use.
