### ISSUE TITLE
Using CCTag as third party

### ISSUE THREAD

**Issue by bubulv** [alicevision/CCTag#71]
First, I add -DCMAKE_INSTALL_PREFIX=$CCTAG_INSTALL at cmake command line and the CCTag make is ok.
Second, in my  CMakeLists.txt file I add the dependency:
   find_package(CCTag CONFIG REQUIRED)
  add_executable(cctagtest yourfile.cpp)
  target_link_libraries(cctagtest PUBLIC CCTag::CCTag)

The location of CCTagConfig.cmake is : CCTag/build/src/generated/CCTagConfig.cmake.
 I do the cmake commond line: cmake .. -DCCTag_DIR=$CCTag/build/src/generated/, but some error as follow：

 CMake Error at CMakeLists.txt:18 (find_package):
  Could not find a package configuration file provided by "CCTag" with any of
  the following names:

    CCTagConfig.cmake
    cctag-config.cmake

  Add the installation prefix of "CCTag" to CMAKE_PREFIX_PATH or set
  "CCTag_DIR" to a directory containing one of the above files.  If "CCTag"
  provides a separate development package or SDK, be sure it has been
  installed.

I don't know how to solve this problem, could you help me.  Thank you very much!

**Comment by fabiencastan** [comment]
You are supposed to run `make install` in the cctag repository (and not use the intermediate build folder).
Then to use it from another repo: `cmake .. -DCCTag_DIR=-DCCTag_DIR=$CCTAG_INSTALL/lib/cmake/CCTag`
As explain [here](https://github.com/alicevision/CCTag/blob/develop/BUILD.md).

**Comment by bubulv** [comment]
It‘s ok!      thank you very much！！！！！

**Comment by fabiencastan** [comment]
Great.
And by the way, any feedback on the lib is welcome!
