### ISSUE TITLE
Always raise assertion on CPU mode. 

### ISSUE THREAD

**Issue by blackball** [alicevision/CCTag#80]
Hi, 

I compiled cctag on Debian 9 with g++ 6.3 in CPU mode and ran it with the sample images. It always give assertions:

```
src/cctag/Identification.cpp:1203: int cctag::identification::identify_step_1(int, const cctag::CCTag&, std::vector<cctag::ImageCut>&, const cv::Mat&, const cctag::Parameters&): Assertion `outerPoints.size() >= 5' failed.
```

The commands was: 
```
./detection -i 01.png -n 3
```

**Comment by simogasp** [comment]
Hi @blackball ,
we are aware of this (see #74), you are better off building in Release mode (`-DCMAKE_BUILD_TYPE:STRING=Release`) to get rid of that (also, release is way faster than debug).

**Comment by blackball** [comment]
Hi @simogasp, Thanks for your quick reply. 

For some reason, passing  -DCMAKE_BUILD_TYPE:STRING=Release will not make it mute assert. What I did is adding add_definitions(-DNDEBUG) into the top level CMakeLists.txt.  It works now.
