### ISSUE TITLE
Fiducial Generation

### ISSUE THREAD

**Issue by johnhable** [alicevision/CCTag#91]
Hi,

Got question/request: What is the algorithm to generate the fiducial markers? I see the PDFs in markersToPrint, but I don't see the 4 ring versions. In my case, I need to print custom patterns like a grid for calibration.

So, what is the algorithm for the radius of the rings of the markers? I see the array for marker identification (CCTagMarkersBank::idFourCrowns) but I'm not sure how those values correspond to the radius of the rings, as well as the appropriate margin size.

Thanks for the help!

John

**Comment by ion1** [comment]
Apologies for a “me too” message, but it has been some time. I would find printable CCTag4 markers useful, is there code to generate them somewhere?

**Comment by ion1** [comment]
Well, here's a generator for markers that may or may not be reverse-engineered correctly. It is untested so far (it turns out Meshroom doesn't actually support them yet). The results are included in the output directory. https://github.com/ion1/cctag-gen

**Comment by simogasp** [comment]
This is now available here
https://github.com/alicevision/CCTag/tree/develop/markersToPrint/generators
Check the doc for the usage:
https://cctag.readthedocs.io/en/doc-first/markers/markers.html
