### ISSUE TITLE
Failed to link OpenCV

### ISSUE THREAD

**Issue by smartnet-club** [alicevision/CCTag#97]
**_Errors:_**
CMakeFiles/detection.dir/detection/main.cpp.o: In function `main':
main.cpp:(.text.startup+0x1b3d): undefined reference to `cv::namedWindow(cv::String const&, int)'
main.cpp:(.text.startup+0x1e84): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
main.cpp:(.text.startup+0x1e9b): undefined reference to `cv::waitKey(int)'
main.cpp:(.text.startup+0x1eaf): undefined reference to `cv::waitKey(int)'

**_Problem with:_**
`find_package(OpenCV REQUIRED core videoio imgproc imgcodecs)`

**_Must be added:_** **highgui**
`find_package(OpenCV REQUIRED core videoio imgproc imgcodecs highgui)`

**Comment by simogasp** [comment]
Hi, thanks for pointing this out.
Could you make a PR with the fix? thanks!

S.

**Comment by smartnet-club** [comment]
We works with cloned version in other VCS. Can't make PR. Sorry.
